version: "3.4"
services:
  neko:
    image: "newsoftwarehq/neko:chromium"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "8888:8001"
      - "8081:8081/tcp"
      - "8082:8082/udp"
    cap_add:
      - SYS_ADMIN
    environment:
      NEKO_SCREEN: "1920x1080@30"
      NEKO_PASSWORD: nwswpass
      NEKO_PASSWORD_ADMIN: nwswadminpass
      NEKO_TCPMUX: 8081
      NEKO_UDPMUX: 8082
      NEKO_ICELITE: 1
      # NEKO_NAT1TO1: 10.0.0.164
      NEKO_NAT1TO1: 192.168.14.83
